### PR TITLE
Add authentication

### PR DESCRIPTION
**Pull request by Cowdrey**

### CODE REVIEW

**Comment by PhilipRead** [comment]
Since some of the commits are failing the Travis CI builds, I think you should probably do a fix up into one commit or just squash.

**Comment by Cowdrey** [comment]
Those commits did fail, but the "fixed specs" commit took care of that. A can squash/merge this whole pr into master when complete. I don't like that it shows those commits are failing (the PR checks are the only ones that matter in the PR), but Travis CI runs on every commit that gets pushed to a branch.  I don't want to squash them before hand because I personally think that makes sorting through the changes more difficult. Especially if I need to revert one due to this PR.

**Comment by PhilipRead** [comment]
But what happens when a poor soul reverts to one of the failing commits? You can do it if you want, but each commit should represent a stable iteration of the code base.

I said my peace. +1 either way.

**Comment by PhilipRead** [comment]
Talked IRL. All good because will squash merge. +1

**Pull request merged**
